### ISSUE TITLE
No such file or directory: 'questions.json'

### ISSUE THREAD

**Issue by lifom** [SocialSisterYi/CxKitty#1]
Traceback (most recent call last):
  File "/app/main.py", line 41, in <module>
    searcher = JsonFileSearcher(
  File "/app/searcher.py", line 58, in __init__
    with open(file_path, 'r', encoding='utf8') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'questions.json'

**Comment by SocialSisterYi** [comment]
在启用刷题功能前，先确保 config.yml 中`searcher->use`字段配置了指定的搜索器，如`jsonFileSearcher`，那么在`searcher->jsonFileSearcher->path`字段就需要指定已存在的 JSON 格式题库，否则程序就会报错
