### ISSUE TITLE
关于课程多选的问题

### ISSUE THREAD

**Issue by bnrh** [SocialSisterYi/CxKitty#102]
![image](https://github.com/SocialSisterYi/CxKitty/assets/58646811/3bb36ef8-85a7-471d-94b9-bb4b2c39b7c2)
我看Readme时发现可以多选课程，但是实际运行时无法一次性选择多门课程进行提交，只能一次一门，是我输入错误还是程序还没开发多选功能呢？
![image](https://github.com/SocialSisterYi/CxKitty/assets/58646811/52a036c8-583d-4a9c-a556-1eeae9ba93cf)

**Comment by lesir5200** [comment]
输入1-3即可

**Comment by bnrh** [comment]
> 输入1-3即可

谢谢哥们这样确实可以选择连续的3门课程但是我想只刷1和3不刷2似乎没有办法？

**Comment by bjxbjx66** [comment]
输入1,3就是只刷1和3(英文逗号)

**Comment by bnrh** [comment]
> 输入1,3就是只刷1和3(英文逗号)

果然可以，哥们太强了（\膜拜脸）
