### ISSUE TITLE
后台保活性

### ISSUE THREAD

**Issue by cyxnzb** [SocialSisterYi/CxKitty#119]
可能是由于启动方式的问题，我在用powershell使用的时候，当电脑进入锁屏模式或者息屏后，程序便不再继续执行（例如刷课模块），希望能够解决

**Comment by SocialSisterYi** [comment]
这个现象与系统调度策略有关，本项目依赖 Python 运行环境部署，是与系统 API 解耦的，且一般情况下应该是前台模式，不会考虑所谓的“后台保活”

**Comment by cyxnzb** [comment]
好滴，谢谢啦
