### ISSUE TITLE
测验 匹配失败  考试无权限

### ISSUE THREAD

**Issue by RichY0608** [SocialSisterYi/CxKitty#122]
![image](https://github.com/SocialSisterYi/CxKitty/assets/125685751/e4f0f36a-5421-45e8-a7e5-49e47db3c108)

**Comment by SocialSisterYi** [comment]
建议检查 Web 端和 APP 端，如果考试未开始或者未达到允许条件，那么无法进行题目的拉取，这个是后端鉴权
