### ISSUE TITLE
CxKitty-服务器版求贡献

### ISSUE THREAD

**Issue by 2061360308** [SocialSisterYi/CxKitty#131]
服务器版即：
- 添加多任务管理类，可多人多账号同时使用，一人分配一个子线程
- 添加网络接口，调用可以获取控制台输出或进行远程输入，可通过浏览器远程连接进行进度查看和操控
- 添加了一个简易的配套前端界面

由于项目采用**Rich**库的输入输出很简单能转换为HTML，所以不到两天时间我个人就简单写出来一个能够浏览器远程操控服务端刷视频的版本，[仓库地址](https://github.com/2061360308/CxKitty)。目前代码还很乱，而且有未知bug，比如后台线程运行几十分钟会莫名消失……

把多个账号同时挂在服务器，能更好的发挥本项目通过api工作，占用资源量小的优点。同时在移动端随时随地就能操作真的好方便，有意参与贡献的来哦。靠我一个人估计坚持不到最后。

**Comment by DiyaDe** [comment]
> 服务器版即：
> 
> * 添加多任务管理类，可多人多账号同时使用，一人分配一个子线程
> * 添加网络接口，调用可以获取控制台输出或进行远程输入，可通过浏览器远程连接进行进度查看和操控
> * 添加了一个简易的配套前端界面
> 
> 由于项目采用**Rich**库的输入输出很简单能转换为HTML，所以不到两天时间我个人就简单写出来一个能够浏览器远程操控服务端刷视频的版本，[仓库地址](https://github.com/2061360308/CxKitty)。目前代码还很乱，而且有未知bug，比如后台线程运行几十分钟会莫名消失……
> 
> 把多个账号同时挂在服务器，能更好的发挥本项目通过api工作，占用资源量小的优点。同时在移动端随时随地就能操作真的好方便，有意参与贡献的来哦。靠我一个人估计坚持不到最后。

我修改了chaoxingWorker.py的代码，希望可以解决，你现在的问题，麻烦下次提供一下日志或者报错代码，我将提交到你的仓库

**Comment by 2061360308** [comment]
感谢，我今天已经找到了问题原因并改正（开始刷视频的时候忘改状态了，所以被当闲置线程删了）。另外这个web项目对我的开发很有参考价值，多谢
