### ISSUE TITLE
登录接口更新了无法登录了

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#132]
![1073400](https://github.com/SocialSisterYi/CxKitty/assets/99703693/06cc3e99-31f4-4aa9-8bf9-6046a8479f79)

**Comment by SocialSisterYi** [comment]
请提供报错日志或者 API 变动详情

**Comment by XXXXBully** [comment]
[cxkitty_13026720927.log](https://github.com/SocialSisterYi/CxKitty/files/14775566/cxkitty_13026720927.log)
易姐你看看

**Comment by XXXXBully** [comment]
[1.log](https://github.com/SocialSisterYi/CxKitty/files/14775578/1.log)
易姐你看看

**Comment by XXXXBully** [comment]
说什么证书错误，不知道是不是要更新python里面的ssl证书
