### ISSUE TITLE
重修的课报错

### ISSUE THREAD

**Issue by NonFelm** [SocialSisterYi/CxKitty#133]
如图：
![image](https://github.com/SocialSisterYi/CxKitty/assets/147258869/8957df42-ce81-4270-b1e9-a874869bddd0)
![image](https://github.com/SocialSisterYi/CxKitty/assets/147258869/3a1c57a6-a9ee-4073-9049-c000a07c8882)

**Comment by NonFelm** [comment]
补充：log
![image](https://github.com/SocialSisterYi/CxKitty/assets/147258869/e044a30a-743b-4096-8d35-d6a20480824b)

**Comment by DiyaDe** [comment]
> 补充：log ![image](https://private-user-images.githubusercontent.com/147258869/317263256-7aa8f523-938d-4841-8b9e-9851e0313af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDM3NTUsIm5iZiI6MTcxMTU0MzQ1NSwicGF0aCI6Ii8xNDcyNTg4NjkvMzE3MjYzMjU2LTdhYThmNTIzLTkzOGQtNDg0MS04YjllLTk4NTFlMDMxM2FmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMjQ0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTliNDZkNzE5N2U5OGRkMGJlMmFkOTYxZmVmMjYwYTU1YjZmMjg4MDgxNjZkMjE4NjE4ODdjYzg3ODIzYWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ISMne8WBPI8x0sD7OZA0mFOw5_EWn30voZ4cd8-NAGE)

你的题库貌似失效了，建议重新找一个题库

**Comment by SocialSisterYi** [comment]
请确保存在至少一个搜索器，即 config.yml 中的`seacher`字段中有一个列表成员，配置语法见示例

**Comment by NonFelm** [comment]
![image](https://github.com/SocialSisterYi/CxKitty/assets/147258869/acf4ef5f-37b5-4467-ac7f-4150c0f2466c)
我配置了enncy题库，也有相应的点数，为什么还会失效呢？

**Comment by SocialSisterYi** [comment]
> ![image](https://private-user-images.githubusercontent.com/147258869/317294513-acf4ef5f-37b5-4467-ac7f-4150c0f2466c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTYzNjIsIm5iZiI6MTcxNTY1NjA2MiwicGF0aCI6Ii8xNDcyNTg4NjkvMzE3Mjk0NTEzLWFjZjRlZjVmLTM3YjUtNDQ2Ny1hYzdmLTQxNTBjMGYyNDY2Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwMzA3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjI3ZGJhOWRjYTZkZDcwMzQ0YTJkMzkyNzdjMWQ2NzFhNzY5Y2FlYzkxMmE0MjkxY2MwZTU4YTVkMGVhODYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qlc-dF1en5X3muyv47a4poyM20bZDBJoqDy81uoT2_w) 我配置了enncy题库，也有相应的点数，为什么还会失效呢？

你的 yaml 格式语法有误，另外，反馈问题时建议对重要 token 做脱敏处理

应当写为：

```yaml
searchers:
  - type: enncySearcher
    token: xxx
```
