### ISSUE TITLE
程序异常退出

### ISSUE THREAD

**Issue by 134527** [SocialSisterYi/CxKitty#137]
![1712024755446](https://github.com/SocialSisterYi/CxKitty/assets/86403935/7f854e93-2cdc-4894-81e1-bfb815510de4)
[Uploading cxkitty_19871375807.log…]()

**Comment by hcunyu** [comment]
+1I have the same problem too

**Comment by DavidMastrenet** [comment]
配置一下搜题来源就行了

**Comment by hahahahahohohohoho** [comment]
> 配置一下搜题来源就行了

在哪里配置啊bro，我试过在CxKitty\resolver\searcher\restapi.py里配置了"网课小工具（Go题）题库"的token但是还是不行。麻烦指点下谢谢╰(✿´⌣`✿)╯♡

**Comment by DavidMastrenet** [comment]
> > 配置一下搜题来源就行了
> 
> 在哪里配置啊bro，我试过在CxKitty\resolver\searcher\restapi.py里配置了"网课小工具（Go题）题库"的token但是还是不行。麻烦指点下谢谢╰(✿´⌣`✿)╯♡

config.yml里面

**Comment by hahahahahohohohoho** [comment]
> > > 配置一下搜题来源就行了
> > 
> > 
> > 在哪里配置啊bro，我试过在CxKitty\resolver\searcher\restapi.py里配置了"网课小工具（Go题）题库"的token但是还是不行。麻烦指点下谢谢╰(✿´⌣`✿)╯♡
> 
> config.yml里面

多谢
