### ISSUE TITLE
答题出错 选择器匹配失败

### ISSUE THREAD

**Issue by vimopqe** [SocialSisterYi/CxKitty#14]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\尤恩\Desktop\xxt脚本\CxKitty-main\main.py:130 in <module>                                     │
│                                                                                                  │
│   127 │   │   classes = api.fetch_classes()  # 拉取该账号下所学的课程                            │
│   128 │   │   course_seq = dialog.select_class(console, classes)  # 进行课程选择                 │
│   129 │   │   for chapter in course_seq:  # 迭代返回课程章节                                     │
│ ❱ 130 │   │   │   fuck_task_worker(chapter)                                                      │
│   131 │   except Exception as err:                                                               │
│   132 │   │   console.print_exception(show_locals=False)                                         │
│   133 │   │   api.logger.error('-----*程序运行异常退出*-----', exc_info=True)                    │
│                                                                                                  │
│ D:\尤恩\Desktop\xxt脚本\CxKitty-main\main.py:83 in fuck_task_worker                              │
│                                                                                                  │
│    80 │   │   │   │   # 试题类型                                                                 │
│    81 │   │   │   │   if isinstance(task_point, ChapterExam) and CONF_EN_EXAM:                   │
│    82 │   │   │   │   │   task_point.mount_searcher(searcher)                                    │
│ ❱  83 │   │   │   │   │   task_point.fill_and_commit(lay_main)                                   │
│    84 │   │   │   │   │   # 开始等待                                                             │
│    85 │   │   │   │   │   wait_for_class(lay_main, CONF_WAIT_EXAM, f'试题《{task_point.title}    │
│    86                                                                                            │
│                                                                                                  │
│ D:\尤恩\Desktop\xxt脚本\CxKitty-main\cxapi\jobs\exam.py:259 in fill_and_commit                   │
│                                                                                                  │
│   256 │   │   │   │   │   JSON.from_data(search_resp, ensure_ascii=False),                       │
│   257 │   │   │   │   │   title='题库接口返回'                                                   │
│   258 │   │   │   │   ))                                                                         │
│ ❱ 259 │   │   │   │   status = self.__fill_answer(question, search_resp)  # 填充选项             │
│   260 │   │   │   │   tb.add_row(                                                                │
│   261 │   │   │   │   │   str(question.q_id),                                                    │
│   262 │   │   │   │   │   question.q_type.name,                                                  │
│                                                                                                  │
│ D:\尤恩\Desktop\xxt脚本\CxKitty-main\cxapi\jobs\exam.py:176 in __fill_answer                     │
│                                                                                                  │
│   173 │   │   log_suffix = f'[{question.value}(Id.{question.q_id})]'                             │
│   174 │   │   self.logger.debug(f'开始填充题目 {log_suffix}')                                    │
│   175 │   │   if search_resp.get('code') == 1:                                                   │
│ ❱ 176 │   │   │   if (r := self.searcher.rsp_query.parse(search_resp)):                          │
│   177 │   │   │   │   search_answer: str = r[0].strip()                                          │
│   178 │   │   │   else:                                                                          │
│   179 │   │   │   │   return False  # JsonPath 选择器匹配失败返回                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'parse'
程序运行出现错误, 请截图保存并附上 log 文件在 issue 提交
![image](https://user-images.githubusercontent.com/116261739/209433792-7f588d8d-def5-40aa-9e41-2593066318bd.png)

**Comment by SocialSisterYi** [comment]
搜索器类重构了，或许该bug已被隐式清除
