### ISSUE TITLE
还是会出现APIError: 章节未开放的问题

### ISSUE THREAD

**Issue by cyxnzb** [SocialSisterYi/CxKitty#141]
但是比较偶发，4个号2个号出现这种情况
 试题《2.5》已结束, 课间等待14/15s             ││     2.5: (1/2) 创新的过程                                │
                                                                        ││ ❱    2.6: (0/2) 创新的原则

**Comment by SocialSisterYi** [comment]
如果章节未开放将无法进行任何数据的拉取，这个是后端鉴权

**Comment by cyxnzb** [comment]
> 如果章节未开放将无法进行任何数据的拉取，这个是后端鉴权

不不，我指的是跟以前那种一样，必须手动去看一下然后才能继续自动看课
