### ISSUE TITLE
今天使用的时候报host='sso.chaoxing.com', port=443

### ISSUE THREAD

**Issue by cyxnzb** [SocialSisterYi/CxKitty#143]
SSLError: HTTPSConnectionPool(host='sso.chaoxing.com', port=443): Max retries exceeded with url:
/apis/login/userLogin4Uname.do (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

**Comment by SocialSisterYi** [comment]
我这边测试没有问题，如有能力使用浏览器或者 OpenSSL 检查 TLS 证书情况，还是发生`CERTIFICATE_VERIFY_FAILED`建议更新系统根证书

**Comment by cyxnzb** [comment]
> 我这边测试没有问题，如有能力使用浏览器或者 OpenSSL 检查 TLS 证书情况，还是发生`CERTIFICATE_VERIFY_FAILED`建议更新系统根证书

系统根证书这边好像不能手动更新吧，然后我本地浏览器访问超星是没啥问题的，所以不太清楚到底哪里出了问题。。。
触发条件是选择账号登录

SSLError: HTTPSConnectionPool(host='sso.chaoxing.com', port=443): Max retries exceeded with url:
/apis/login/userLogin4Uname.do (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
