### ISSUE TITLE
报错说重定向问题

### ISSUE THREAD

**Issue by 2061360308** [SocialSisterYi/CxKitty#146]
输出为下：
测试环境：docker，pip安装库。
系统: windows/ ubuntu

/app/main.py:350 in <module>                                                                     │
│                                                                                                  │
│   347 │   # 会话存档为空                                                                         │
│   348 │   else:                                                                                  │
│   349 │   │   console.print("[yellow]会话存档为空, 请登录账号")                                  │
│ ❱ 350 │   │   dialog.login(console, api)                                                         │
│   351 │   logger.info("\n-----*任务开始执行*-----")                                              │
│   352 │   logger.info(f"Ver. {__version__}")                                                     │
│   353 │   dialog.accinfo(console, api)                                                           │
│                                                                                                  │
│ /app/dialog.py:101 in login                                                                      │
│                                                                                                  │
│    98 │   │   else:                                                                              │
│    99 │   │   │   passwd = Prompt.ask("[yellow]请输入密码 (内容隐藏)", password=True, console=   │
│   100 │   │   │   tui_ctx.print('')                                                              │
│ ❱ 101 │   │   │   status, result = api.login_passwd(uname, passwd)                               │
│   102 │   │   │   if status:                                                                     │
│   103 │   │   │   │   tui_ctx.print("[green]登录成功")                                           │
│   104 │   │   │   │   tui_ctx.print(result)                                                      │
│                                                                                                  │
│ /app/cxapi/api.py:82 in login_passwd                                                             │
│                                                                                                  │
│    79 │   │   cryptor = AES.new(KEY, AES.MODE_CBC, KEY)                                          │
│    80 │   │   passwd = base64.b64encode(cryptor.encrypt(pad(passwd.encode(), 16))).decode()      │
│    81 │   │                                                                                      │
│ ❱  82 │   │   resp = self.session.post(                                                          │
│    83 │   │   │   API_LOGIN_WEB,                                                                 │
│    84 │   │   │   data={                                                                         │
│    85 │   │   │   │   "fid": -1,                                                                 │
│                                                                                                  │
│ /app/.venv/lib/python3.10/site-packages/requests/sessions.py:637 in post                         │
│                                                                                                  │
│   634 │   │   :rtype: requests.Response                                                          │
│   635 │   │   """                                                                                │
│   636 │   │                                                                                      │
│ ❱ 637 │   │   return self.request("POST", url, data=data, json=json, **kwargs)                   │
│   638 │                                                                                          │
│   639 │   def put(self, url, data=None, **kwargs):                                               │
│   640 │   │   r"""Sends a PUT request. Returns :class:`Response` object.                         │
│                                                                                                  │
│ /app/cxapi/session.py:210 in request                                                             │
│                                                                                                  │
│   207 │   │   │   Response: 响应数据                                                             │
│   208 │   │   """                                                                                │
│   209 │   │   try:                                                                               │
│ ❱ 210 │   │   │   resp = super().request(*args, **kwargs)                                        │
│   211 │   │   except requests.ConnectionError as e:                                              │
│   212 │   │   │   self.__request_retry_cnt += 1                                                  │
│   213 │   │   │   self.logger.warning(f"连接错误 {e.__str__()}")                                 │
│                                                                                                  │
│ /app/.venv/lib/python3.10/site-packages/requests/sessions.py:589 in request                      │
│                                                                                                  │
│   586 │   │   │   "allow_redirects": allow_redirects,                                            │
│   587 │   │   }                                                                                  │
│   588 │   │   send_kwargs.update(settings)                                                       │
│ ❱ 589 │   │   resp = self.send(prep, **send_kwargs)                                              │
│   590 │   │                                                                                      │
│   591 │   │   return resp                                                                        │
│   592                                                                                            │
│                                                                                                  │
│ /app/.venv/lib/python3.10/site-packages/requests/sessions.py:725 in send                         │
│                                                                                                  │
│   722 │   │   if allow_redirects:                                                                │
│   723 │   │   │   # Redirect resolving generator.                                                │
│   724 │   │   │   gen = self.resolve_redirects(r, request, **kwargs)                             │
│ ❱ 725 │   │   │   history = [resp for resp in gen]                                               │
│   726 │   │   else:                                                                              │
│   727 │   │   │   history = []                                                                   │
│   728                                                                                            │
│                                                                                                  │
│ /app/.venv/lib/python3.10/site-packages/requests/sessions.py:725 in <listcomp>                   │
│                                                                                                  │
│   722 │   │   if allow_redirects:                                                                │
│   723 │   │   │   # Redirect resolving generator.                                                │
│   724 │   │   │   gen = self.resolve_redirects(r, request, **kwargs)                             │
│ ❱ 725 │   │   │   history = [resp for resp in gen]                                               │
│   726 │   │   else:                                                                              │
│   727 │   │   │   history = []                                                                   │
│   728                                                                                            │
│                                                                                                  │
│ /app/.venv/lib/python3.10/site-packages/requests/sessions.py:191 in resolve_redirects            │
│                                                                                                  │
│   188 │   │   │   │   resp.raw.read(decode_content=False)                                        │
│   189 │   │   │                                                                                  │
│   190 │   │   │   if len(resp.history) >= self.max_redirects:                                    │
│ ❱ 191 │   │   │   │   raise TooManyRedirects(                                                    │
│   192 │   │   │   │   │   f"Exceeded {self.max_redirects} redirects.", response=resp             │
│   193 │   │   │   │   )                                                                          │
│   194                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by 2061360308** [comment]
已解决，阿里云服务器的网络问题。使用VPN代理后正常登录

**Comment by cyxnzb** [comment]
> 已解决，阿里云服务器的网络问题。使用VPN代理后正常登录

我本地也出现了这样的问题，请问应该如何解决，一直提示SSL连接失败

**Comment by 2061360308** [comment]
> > 已解决，阿里云服务器的网络问题。使用VPN代理后正常登录
> 
> 我本地也出现了这样的问题，请问应该如何解决，一直提示SSL连接失败

我的这种情况是在浏览器访问学习通也会被拒绝，不是项目的问题。如果你在本地访问浏览器可以正常访问学习通，但是本项目报这个错误的话我也暂时没有任何办法。如果你自己浏览器登学习通也进不去的话，嗯，这种情况直接上报老师们就好，哈哈。
