### ISSUE TITLE
考试时出现滑块问题

### ISSUE THREAD

**Issue by lpy30m** [SocialSisterYi/CxKitty#149]
已经解决学习通滑块问题，如有需要联系我免费开源提供

**Comment by SocialSisterYi** [comment]
能提供具体截图/日志/或者url吗？

**Comment by lpy30m** [comment]
> 能提供具体截图/日志/或者url吗？

这种滑块，这种滑块在学习通是通用的，点击进入考试也是这个滑块，我考试已经结束，但可以触发相同滑块的url是这个https://user.dayainfo.com/show/login

**Comment by XXXXBully** [comment]
是的正如这个哥们所说只要触发风控或者考试都能出现

**Comment by XXXXBully** [comment]
是的正如这个哥们所说只要触发风控或者考试都能出现

**Comment by QiqiFire** [comment]
同样出现滑块问题。考试进入的时候需要滑块验证。此时终端无法进入考试显示无权限访问。
![image](https://github.com/SocialSisterYi/CxKitty/assets/85268447/f66314fe-6389-4e82-ad07-d6cf522f78a7)

**Comment by QiqiFire** [comment]
> 已经解决学习通滑块问题，如有需要联系我免费开源提供

需要啊我哥，还有这个软件，如果考试只允许手机端考试，这个程序可以用吗

**Comment by XXXXBully** [comment]
哥们开源看看，我想知道咋解决的，滑块咋打码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 中午12:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 考试时出现滑块问题 (Issue #149)




  
已经解决学习通滑块问题，如有需要联系我免费开源提供
  
需要啊我哥，还有这个软件，如果考试只允许手机端考试，这个程序可以用吗

**Comment by XXXXBully** [comment]
你们会遇到人脸上传失败的问题吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月15日(周三) 中午12:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 考试时出现滑块问题 (Issue #149)




 
同样出现滑块问题。考试进入的时候需要滑块验证。此时终端无法进入考试显示无权限访问。
 image.png (view on web)

**Comment by XXXXBully** [comment]
> 已经解决学习通滑块问题，如有需要联系我免费开源提供

哥们开源看看，我想知道咋解决的，滑块咋打码

**Comment by 2173505570** [comment]
> 已经解决学习通滑块问题，如有需要联系我免费开源提供



> 已经解决学习通滑块问题，如有需要联系我免费开源提供

哥，求教，captchaKey和token的值生成逻辑通过断点大概明白了，js扒代码运行不出结果，狠狠的求教了，方便的话加我qq:2173505570

**Comment by cyxnzb** [comment]
+1

**Comment by vimopqe** [comment]
> 已经解决学习通滑块问题，如有需要联系我免费开源提供

哥哥，可以提供下么

**Comment by XXXXBully** [comment]
楼主已经解决了，可以docker部署使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月20日(周二) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 考试时出现滑块问题 (Issue #149)




  
已经解决学习通滑块问题，如有需要联系我免费开源提供
  
哥哥，可以提供下么

**Comment by vimopqe** [comment]
> 楼主已经解决了，可以docker部署使用
> […](#)
> ---原始邮件--- 发件人： ***@***.***> 发送时间: 2024年8月20日(周二) 下午4:17 收件人： ***@***.***>; 抄送： ***@***.******@***.***>; 主题： Re： [SocialSisterYi/CxKitty] 考试时出现滑块问题 （Issue #149） 已经解决学习通滑块问题，如有需要联系我免费开源提供 哥哥，可以提供下么 — 直接回复此邮件，在GitHub上查看，或取消订阅。 您收到此消息是因为您发表了评论。消息 ID： ***@***.***>

最新的 我用着 然后输出那个错误的地方，还是安全验证不通过，是哪个地方错了么

**Comment by XXXXBully** [comment]
不知道你具体怎么操作的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月20日(周二) 下午4:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 考试时出现滑块问题 (Issue #149)




  
楼主已经解决了，可以docker部署使用
 …
 ---原始邮件--- 发件人： @.&gt; 发送时间: 2024年8月20日(周二) 下午4:17 收件人： @.&gt;; 抄送： @.@.&gt;; 主题： Re： [SocialSisterYi/CxKitty] 考试时出现滑块问题 （Issue #149） 已经解决学习通滑块问题，如有需要联系我免费开源提供 哥哥，可以提供下么 — 直接回复此邮件，在GitHub上查看，或取消订阅。 您收到此消息是因为您发表了评论。消息 ID： @.***&gt;
  
最新的 我用着 然后输出那个错误的地方，还是安全验证不通过，是哪个地方错了么

**Comment by lpy30m** [comment]
已开源

**Comment by SocialSisterYi** [comment]
> 已开源

能否提供仓库地址

**Comment by lpy30m** [comment]
> > 已开源
> 
> 能否提供仓库地址
没问题
https://github.com/lpy30m/xuexitong

**Comment by lpy30m** [comment]
> > 已开源
> 
> 能否提供仓库地址

如果可以，希望您能把我加入贡献者

**Comment by SocialSisterYi** [comment]
> > > 已开源
> > 
> > 能否提供仓库地址
> 没问题
> https://github.com/lpy30m/xuexitong

好的谢谢
