### ISSUE TITLE
docker出现 Searcher "OpenAISearcher" not found

### ISSUE THREAD

**Issue by DR-lin-eng** [SocialSisterYi/CxKitty#150]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /app/main.py:372 in <module>                                                                     │
│                                                                                                  │
│   369 │   │   for task_obj in ClassSelector(command, classes):                                   │
│   370 │   │   │   # 章节容器 执行章节任务                                                        │
│   371 │   │   │   if isinstance(task_obj, ChapterContainer):                                     │
│ ❱ 372 │   │   │   │   fuck_task_worker(task_obj)                                                 │
│   373 │   │   │                                                                                  │
│   374 │   │   │   # 考试对象 执行考试任务                                                        │
│   375 │   │   │   elif isinstance(task_obj, ExamDto):                                            │
│                                                                                                  │
│ /app/main.py:205 in fuck_task_worker                                                             │
│                                                                                                  │
│   202 │   │   │   │   │   │   │   │   continue                                                   │
│   203 │   │   │   │   │   │   │   task_point.fetch_all()                                         │
│   204 │   │   │   │   │   │   │   # 实例化解决器                                                 │
│ ❱ 205 │   │   │   │   │   │   │   resolver = QuestionResolver(                                   │
│   206 │   │   │   │   │   │   │   │   exam_dto=task_point,                                       │
│   207 │   │   │   │   │   │   │   │   fallback_save=config.WORK["fallback_save"],                │
│   208 │   │   │   │   │   │   │   │   fallback_fuzzer=config.WORK["fallback_fuzzer"],            │
│                                                                                                  │
│ /app/resolver/question.py:194 in __init__                                                        │
│                                                                                                  │
│   191 │   │   self.persubmit_delay = persubmit_delay                                             │
│   192 │   │   self.auto_final_submit = auto_final_submit                                         │
│   193 │   │   self.cb_confirm_submit = cb_confirm_submit                                         │
│ ❱ 194 │   │   self.searcher = load_searcher()  # 从配置文件加载搜索器                            │
│   195 │   │                                                                                      │
│   196 │   │   self.tui_ctx = Layout(name="Resolver")  # 当前类所属 TUI 的 ctx                    │
│   197 │   │   self.mistakes = []                                                                 │
│                                                                                                  │
│ /app/resolver/question.py:69 in load_searcher                                                    │
│                                                                                                  │
│    66 │   │   typename = searcher_conf["type"]                                                   │
│    67 │   │   typename = typename[0].upper() + typename[1:]                                      │
│    68 │   │   if typename not in SEARCHERS:                                                      │
│ ❱  69 │   │   │   raise AttributeError(f'Searcher "{typename}" not found')                       │
│    70 │   │   del searcher_conf["type"]                                                          │
│    71 │   │   # 动态加载搜索器类                                                                 │
│    72 │   │   searcher.add(SEARCHERS[typename](**searcher_conf))                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: Searcher "OpenAISearcher" not found
程序运行出现错误, 请截图保存并附上 log 文件在 issue 提交

**Comment by SocialSisterYi** [comment]
Docker Hub 发布的版本是 v0.4.5，没有 OpenAISearcher 搜索器，所以无法使用，建议自行构建镜像或者等待后续版本发布

**Comment by DR-lin-eng** [comment]
ok
