### ISSUE TITLE
考试有问题 - 安全验证不通过，请重新验证

### ISSUE THREAD

**Issue by vimopqe** [SocialSisterYi/CxKitty#167]
│                                                                                                  │
│   571 │   │   │   if t.text == "考试已经提交":                                                   │
│   572 │   │   │   │   raise ExamIsCommitted                                                      │
│   573 │   │   │   elif t.text in ("无权限访问！", "当前用户账号发生异常，无法进行考试", "当前    │
│ ❱ 574 │   │   │   │   raise ExamAccessDenied(t.text)                                             │
│   575 │   │   │   elif t.text == "无效参数！":                                                   │
│   576 │   │   │   │   raise ExamInvalidParams(t.text)                                            │
│   577 │   │   │   else:                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ExamAccessDenied: 试题无权限访问
程序运行出现错误, 请截图保存并附上 log 文件在 issue 提交

在这里看了下 在开始考试的时候出现了   安全验证不通过，请重新验证  这个得解决一下

**Comment by SocialSisterYi** [comment]
目前修复该问题的版本还未构建docker包上传，请自行clone并构建
