### ISSUE TITLE
新版app的UA升级了

### ISSUE THREAD

**Issue by mainblog** [SocialSisterYi/CxKitty#168]
升级后好像多了schild参数的加密：
Dalvik/2.1.0 (Linux; U; Android 12; M2012K11AC Build/SKQ1.220201.001) (schild:84955fc7ad1bc17aab875bc3f039c3ae) (device:GFE4J) Language/zh_CN com.chaoxing.mobile/ChaoXingStudy_3_6.3.2_android_phone_1060_235 (@Kalimdor)_31ebe0572432492ab710573d39803e2f

**Comment by guowang23333** [comment]
擦了看到了。。。看看咋搞吧
