### ISSUE TITLE
怎么对接其他的题库呀，如果有别的题库token的话

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#17]

**Comment by XXXXBully** [comment]
有想法继续开发这个程序，有没有讨论一下如何添加一个考试的功能

**Comment by SocialSisterYi** [comment]
如需对接在线题库，可以在配置文件种`restApiSearcher`字段下修改配置，如请求头部、query或body参数等

**Comment by SocialSisterYi** [comment]
> 有想法继续开发这个程序，有没有讨论一下如何添加一个考试的功能

考试部分已经在计划中了，后面有精力再开发，以及请不要在同一个 issue 下提不同的两个话题

**Comment by XXXXBully** [comment]
好的好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月6日(周五) 晚上11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 怎么对接其他的题库呀，如果有别的题库token的话 (Issue #17)




  
有想法继续开发这个程序，有没有讨论一下如何添加一个考试的功能
  
考试部分已经在计划中了，后面有精力再开发，以及请不要在同一个 issue 下提不同的两个话题

**Comment by XXXXBully** [comment]
感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月6日(周五) 晚上11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 怎么对接其他的题库呀，如果有别的题库token的话 (Issue #17)




 
如需对接在线题库，可以在配置文件种restApiSearcher字段下修改配置，如请求头部、query或body参数等
