### ISSUE TITLE
小白问个问题

### ISSUE THREAD

**Issue by youwusui** [SocialSisterYi/CxKitty#3]
![084f8a1b2a98add9a72b8d4fd9c2b02](https://user-images.githubusercontent.com/118417660/202352620-5d0c2b34-a7ea-453f-ace9-e267ef95aa97.png)
我实在不懂这个怎么解决，昨天从下午弄到晚上三点我也没弄明白怎么搞，可以教教我这是为啥吗？

**Comment by SocialSisterYi** [comment]
尝试使用linux安装，这是lxml模块安装的问题

**Comment by youwusui** [comment]
好的，谢谢

**Comment by Cro3odile** [comment]
![5LECN(_3(8IE(7FJA(~6$IR](https://user-images.githubusercontent.com/63222351/208682075-d7e5897d-b499-4e7c-9ee9-8ddbf7f00809.png)
求教一下这种情况怎么办 beautifulsoup4安装了的 lxml版本也和Python版本对的上 就是报错
