### ISSUE TITLE
AttributeError:“NoneType”对象没有属性“text”   ，用API在线题库，显示jsonpath没有compile方法 

### ISSUE THREAD

**Issue by w1714085706** [SocialSisterYi/CxKitty#31]
python版本号为3.10
AttributeError: 'NoneType' object has no attribute 'text'

![1](https://user-images.githubusercontent.com/117039920/232117402-e72ea83f-ec41-4151-98fb-7dc94fc58c26.png)

**Comment by Esdrim** [comment]
@w1714085706 同样的问题，Python版本为3.11
![image](https://user-images.githubusercontent.com/97580517/232203293-2815d24e-c906-4deb-9cdf-9e080ebbe270.png)
查看代码是这段
![image](https://user-images.githubusercontent.com/97580517/232203572-7e1d0db8-54b1-4d6d-8a93-5ec2c24c35e4.png)
于是在上面保存到网页，发现是题目查找不对（超星真的空）
![image](https://user-images.githubusercontent.com/97580517/232203780-78069c3d-83c8-43e5-9ff4-ed07aea37563.png)
按照上面的改成这样
![image](https://user-images.githubusercontent.com/97580517/232204339-cf0789c9-6f95-45af-b792-e2bf511fb8e6.png)
问题解决
![image](https://user-images.githubusercontent.com/97580517/232204245-d5e43f55-b783-4664-84f9-5f00472be9b0.png)

**Comment by w1714085706** [comment]
> @w1714085706同样的问题，Python版本为3.11 查看代码是这一段 是在上面保存到网页，发现是题目找到不对（星星真实的空间） 按照片上面的 改成 ![图片](https://user-images.githubusercontent.com/97580517/232203293-2815d24e-c906-4deb-9cdf-9e080ebbe270.png) ![图片](https://user-images.githubusercontent.com/97580517/232203572-7e1d0db8-54b1-4d6d-8a93-5ec2c24c35e4.png) ![图片](https://user-images.githubusercontent.com/97580517/232203780-78069c3d-83c8-43e5-9ff4-ed07aea37563.png) ![图片](https://user-images.githubusercontent.com/97580517/232204339-cf0789c9-6f95-45af-b792-e2bf511fb8e6.png) ![图片](https://user-images.githubusercontent.com/97580517/232204245-d5e43f55-b783-4664-84f9-5f00472be9b0.png)


你用api在线搜索器会出现jsonpath不存在compile属性？
![1](https://user-images.githubusercontent.com/117039920/232205534-3bb893be-1f2e-4f15-8d62-f1d42782d879.png)

**Comment by Esdrim** [comment]
我在jsonpath的库中有这个compile属性
![image](https://user-images.githubusercontent.com/97580517/232205892-b971cc94-6edd-4a92-ac3c-27b596eb179d.png)

**Comment by Esdrim** [comment]
@w1714085706 如下是版本
![image](https://user-images.githubusercontent.com/97580517/232206190-2391b76a-17d6-436d-b3f3-b8d07098149e.png)

**Comment by DiyaDe** [comment]
> 
![QQ截图20230423190833](https://user-images.githubusercontent.com/104015495/233836322-a5ce6728-13d9-439a-a5f3-b4a3ca72881a.png)
我按照的方案，进行修改了，但是问题依旧存在，不知道是什么原因。麻烦大佬，有空的时候看看，谢谢大佬

**Comment by DiyaDe** [comment]
> > 
> 
> ![QQ截图20230423190833](https://user-images.githubusercontent.com/104015495/233836322-a5ce6728-13d9-439a-a5f3-b4a3ca72881a.png) 我按照你的方案，进行修改了，但是问题依旧存在，不知道是什么原因。 麻烦大佬，有空的时候看看，谢谢大佬

**Comment by DiyaDe** [comment]
> > 
> 
> ![QQ截图20230423190833](https://user-images.githubusercontent.com/104015495/233836322-a5ce6728-13d9-439a-a5f3-b4a3ca72881a.png) py版本号3.10.6。
 我按照的方案，进行修改了，但是问题依旧存在，不知道是什么原因。 麻烦大佬，有空的时候看看，谢谢大佬
