### ISSUE TITLE
账号密码登录没有反应

### ISSUE THREAD

**Issue by gaonan98** [SocialSisterYi/CxKitty#34]
你好，我尝试登录发现目前只有二维码可以登录，用账号密码登陆的话程序一直在运行但是无法登录
![image](https://user-images.githubusercontent.com/61961696/233273127-0d34f2b8-9590-4f18-acc7-b2ab621324fd.png)

**Comment by SocialSisterYi** [comment]
由于二维码登录并不保存密码，所有无法进行（自动/手动）重登操作

但现在不知道你的账号是否使用密码登录也存在未知问题？
