### ISSUE TITLE
刷课途中闪退

### ISSUE THREAD

**Issue by tianboyi** [SocialSisterYi/CxKitty#35]
刷课途中闪退，只能选择下一门新课程，已刷过的仍然闪退，只要发生闪退就只能找新课程刷。
[cxkitty_15001122201.log](https://github.com/SocialSisterYi/CxKitty/files/11303995/cxkitty_15001122201.log)

**Comment by SocialSisterYi** [comment]
该问题可能是网络连接不稳定，也有可能是接口风控导致，现在已经增加打码机制，修复了该 bug
