### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by ayu3356** [SocialSisterYi/CxKitty#36]
![GJ3I2S87WWI 7KEYVMKTKT8](https://user-images.githubusercontent.com/82030911/234332568-f20b278d-f40f-4b0c-b58a-93eb174013c1.png)
[cxkitty_15001122201.log](https://github.com/SocialSisterYi/CxKitty/files/11324412/cxkitty_15001122201.log)

**Comment by Cro3odile** [comment]
![image](https://user-images.githubusercontent.com/63222351/236379766-26b8bf65-1cb2-4627-a208-b1e98580523b.png)

**Comment by kitUIN** [comment]
@SocialSisterYi 这个issue可以关了吧
