### ISSUE TITLE
大佬，登录成功后报错

### ISSUE THREAD

**Issue by 19819068211** [SocialSisterYi/CxKitty#4]
扫描二维码登录后：
![image](https://user-images.githubusercontent.com/66981884/202892610-766fd940-9afe-4bb1-905f-14bb6271a81f.png)
账号密码登录后：
![image](https://user-images.githubusercontent.com/66981884/202892628-6f84365b-bd46-4593-9ff7-b9f7c85390e9.png)

**Comment by SocialSisterYi** [comment]
请提供此账号登录后 http://passport2.chaoxing.com/mooc/accountManage 页面上的所有html源码

**Comment by SocialSisterYi** [comment]
该bug已解决，是因为html标签的匹配失败，现在已经更换用户信息的获取接口
