### ISSUE TITLE
可以添加一个匹配不到题目随机选择并提交

### ISSUE THREAD

**Issue by cx073** [SocialSisterYi/CxKitty#40]
在每一章都有章节测验，这个章节测验是无关紧要的，但是章节测验不提交就看不了下一章导致程序报错，可以在章节测验搜不到题目的时候随机填写或者“都选B”然后点提交以便顺利进入下一章

**Comment by SocialSisterYi** [comment]
在配置文件 config.yml 中，修改`work->fallback_fuzzer`为`true`即可
