### ISSUE TITLE
为啥安装上lxml之后也老是报错，我用poetry命令安装4.9.1安装不上，转而又安装4.9.2就报错

### ISSUE THREAD

**Issue by taojinying** [SocialSisterYi/CxKitty#41]
这是用poetry install安装报错截图
![2222222222](https://github.com/SocialSisterYi/CxKitty/assets/101920788/62a15360-7a24-44a0-ae5b-7809cd76cb18)
下边这个是百度搜的教程安装lxml4.9.2后的报错
![111111111111111111](https://github.com/SocialSisterYi/CxKitty/assets/101920788/3e6c1265-c993-4f29-8399-9d9f6a3e6fd4)
这些都咋解决啊

**Comment by kitUIN** [comment]
尝试使用python3.10试试？

**Comment by taojinying** [comment]
> 尝试使用python3.10试试？

好，我试一试，我记得之前我在ubuntu上运行成功过，现在转到了Windows就不行了，实在不行就再用ubuntu试试
