### ISSUE TITLE
下载完这个最新版本的之后，观看完视频直接报错

### ISSUE THREAD

**Issue by taojinying** [SocialSisterYi/CxKitty#43]
![屏幕截图 2023-06-22 182710](https://github.com/SocialSisterYi/CxKitty/assets/101920788/a934087b-05ad-4549-97c3-77ffef64d16b)

**Comment by SocialSisterYi** [comment]
请检查你的网络环境，如 wifi 质量 DNS 配置等，如果都没问题，可以重新启动并选择目标课程

**Comment by taojinying** [comment]
> 课程

重启了一下，没问题了
