### ISSUE TITLE
运行主程序时打开立马闪退

### ISSUE THREAD

**Issue by Fearless1027** [SocialSisterYi/CxKitty#46]
运行主程序时打开立马闪退，使用IDLE打开却可以成功运行，这是为什么？

**Comment by kitUIN** [comment]
有日志吗

**Comment by Fearless1027** [comment]
日志也没有，只有在IDLE运行的时候才出现日志，Python 3.10.11

**Comment by Fearless1027** [comment]
多嘴问一句，如何提取这个试题呀？

**Comment by SocialSisterYi** [comment]
> 日志也没有，只有在IDLE运行的时候才出现日志，Python 3.10.11

建议系统使用终端或 VSCode/PyCharm 等等 IDE 运行及调试，不要使用 IDLE

**Comment by SocialSisterYi** [comment]
> 多嘴问一句，如何提取这个试题呀？

如要提取作业试题，请在 config 中配置导出模式，如要提速考试试题，则在选择考试时序号前加e，但均需要在 config 中配置导出路径
