### ISSUE TITLE
手机刷课

### ISSUE THREAD

**Issue by Zoe-create** [SocialSisterYi/CxKitty#5]
您好，可以实习手机刷课吗，以前有个项目可以用termux执行，但是停止维护了

**Comment by SocialSisterYi** [comment]
可以的，需要安装python和poetry，这里有一些需要注意的

**Comment by Zoe-create** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Zoe-create** [comment]
小白不太会操作😭
