### ISSUE TITLE
export()函数不工作

### ISSUE THREAD

**Issue by FT1142558190** [SocialSisterYi/CxKitty#51]
for task_point in chap[index]:
                try:
                    # 开始分类讨论任务点类型
                    # 章节测验类型
                    if isinstance(task_point, PointWorkDto) and (config.WORK_EN or config.WORK["export"] is True):
                        
                       
                        # 导出作业试题
                        if config.WORK["export"] is True:

                            # 预拉取任务点数据
                            task_point.pre_fetch()
                            # 保存 json 文件
                            task_point.export(config.EXPORTPATH / f"work_{task_point.work_id}.json")

这是main.py的一段代码config.WORK["export"] 为Ture 可是export(）怎么都不运行

**Comment by FT1142558190** [comment]
学会了单步执行我的代码的debug方式再让我调试调试

**Comment by FT1142558190** [comment]
字符串‘True’不是True
if 'True' is True:
    print('asdasd')
else:
    print('as22')

**Comment by FT1142558190** [comment]
解决了，感谢

**Comment by Fearless1027** [comment]
哥们你是怎么解决的
