### ISSUE TITLE
输入完账号密码就报错

### ISSUE THREAD

**Issue by taojinying** [SocialSisterYi/CxKitty#52]
![屏幕截图 2023-09-03 221215](https://github.com/SocialSisterYi/CxKitty/assets/101920788/f20fa7dc-d9c2-4255-a085-c14572e718d6)

**Comment by SocialSisterYi** [comment]
该 bug 系正在开发中的“人脸识别提示识别与提交”功能实现不完全所致，具体因为`file_path`路径不存在却写入文件导致异常，最新 commit https://github.com/SocialSisterYi/CxKitty/commit/df76d8e7737ab484a4bf65bce169fe455e669e23 已修复

若无程序异常调试能力，建议自行下载 [Releases](https://github.com/SocialSisterYi/CxKitty/releases) 中发布的正式版源码使用，或 CI 构建的 Docker 包、exe 可执行文件
