### ISSUE TITLE
课程meta返回不存在教师名导致的异常

### ISSUE THREAD

**Issue by ilh-github** [SocialSisterYi/CxKitty#53]
![image](https://github.com/SocialSisterYi/CxKitty/assets/53887385/a850b1c5-6103-4ac1-97de-591aa8b617f6)

**Comment by ilh-github** [comment]
我解决了：有的json缺少属性。
![image](https://github.com/SocialSisterYi/CxKitty/assets/53887385/5c67ccbc-5f11-42a0-aaf2-5cae2d8e50a5)

**Comment by SocialSisterYi** [comment]
这是由于一些课程不存在教师字段导致的，可以提交一个 PR，另外建议把`空`改为`未知`

**Comment by ilh-github** [comment]
麻烦您嘞。
