### ISSUE TITLE
视频预拉取错误

### ISSUE THREAD

**Issue by taojinying** [SocialSisterYi/CxKitty#54]
![屏幕截图 2023-09-04 153921](https://github.com/SocialSisterYi/CxKitty/assets/101920788/080dc910-25b2-4e48-a66c-fccc74b3469f)
是不是跟章节带锁有关呢？

**Comment by taojinying** [comment]
![Uploading 2.png…]()

**Comment by taojinying** [comment]
![2](https://github.com/SocialSisterYi/CxKitty/assets/101920788/e4baca3b-a5af-471d-a73e-db177880f3c0)

**Comment by SocialSisterYi** [comment]
如果没有调试能力，可以把账号密码私发到我的邮箱（github 个人主页有），这边登录后帮你测试程序具体故障

**Comment by taojinying** [comment]
> 如果没有调试能力，可以把账号密码私发到我的邮箱（github 个人主页有），这边登录后帮你测试程序具体故障

好的，谢谢 已经发您邮箱了

**Comment by SocialSisterYi** [comment]
经过测试，发现异常产生点在拉取 Attachment 数据的函数中，即章节任务点卡片页面

![image](https://github.com/SocialSisterYi/CxKitty/assets/45892418/6aab9fc8-5919-4c66-aab5-7da80744082a)

该页面为报错特殊页打开效果如下，是服务端限制，本项目无法解决

![image](https://github.com/SocialSisterYi/CxKitty/assets/45892418/55f26b7a-c0b7-46ff-8a4c-400c650f1061)

最新 commit https://github.com/SocialSisterYi/CxKitty/commit/3ea8f02c2a8eda10b11980daa865a8c5f15c34a4 加入了这个报错信息的捕获，可明确在 TUI 以及 log 文件中展示

![image](https://github.com/SocialSisterYi/CxKitty/assets/45892418/9329dabb-4ad3-46cf-91f8-433efa0186a3)

`2.3.1`这个章节有两个任务点，目前视频已经完成，把作业完成大概就不会报错了
