### ISSUE TITLE
特定视频拉取attachment报错

### ISSUE THREAD

**Issue by AlwaysLazy21** [SocialSisterYi/CxKitty#59]
[日志信息]
(https://github.com/SocialSisterYi/CxKitty/files/12568384/cxkitty_1xxxxxxxxxxx.log)
![Snipaste_2023-09-10_22-15-44](https://github.com/SocialSisterYi/CxKitty/assets/95759005/866801ad-3474-441f-9dd4-7f882698ee95)
![Snipaste_2023-09-10_22-19-12](https://github.com/SocialSisterYi/CxKitty/assets/95759005/3b0ae736-18fd-4e68-9b99-6a330d9e7b77)
网页上面是正常的

**Comment by SocialSisterYi** [comment]
该 bug 可能与 #58 相同，都为 attachment 的 json 解析异常，请私发邮件账号密码，或打断点输出 resp.text 内容并贴上

**Comment by SocialSisterYi** [comment]
#58 中的 BUG 已经修复，请拉取最新 commit 自行构建并测试
