### ISSUE TITLE
使用构造的可执行exe文件无法登录

### ISSUE THREAD

**Issue by Cai231** [SocialSisterYi/CxKitty#60]
账号密码登录方式下，输入密码无反应。二维码登录方式下，输出的二维码为乱码
<img width="720" alt="2023-09-16_075437" src="https://github.com/SocialSisterYi/CxKitty/assets/95583648/099121a5-198e-4434-b645-5e9c4d866671">

**Comment by Dragonte6967** [comment]
有可能是终端字体有问题

**Comment by Dragonte6967** [comment]
密码输入时不显示，输完密码直接回车登录就行

**Comment by SocialSisterYi** [comment]
请使用 windows terminal 等终端模拟器应用，不要使用 windows 系统默认的（cmd）
