### ISSUE TITLE
这个不是exe吗？怎么运行的

### ISSUE THREAD

**Issue by 1836360570** [SocialSisterYi/CxKitty#61]

**Comment by Dragonte6967** [comment]
action里面找


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月18日(周一) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [SocialSisterYi/CxKitty] 这个不是exe吗？怎么运行的 (Issue #61)




 
&mdash;
