### ISSUE TITLE
答题闪退

### ISSUE THREAD

**Issue by Cai231** [SocialSisterYi/CxKitty#62]
运行到答题部分就会闪退，日志如下
<img width="1280" alt="2023-09-20_215441" src="https://github.com/SocialSisterYi/CxKitty/assets/95583648/0f19a4e9-1256-466e-89d1-35386fd61f2c">
<img width="1280" alt="2023-09-20_215320" src="https://github.com/SocialSisterYi/CxKitty/assets/95583648/582259c4-764f-410c-8ec2-b4a5585eddc2">

**Comment by SocialSisterYi** [comment]
请在 config.yml 中至少配置一个题库接口，或者关闭自动答题使能开关
