### ISSUE TITLE
请教JSON格式题库api如何请求

### ISSUE THREAD

**Issue by 19819068211** [SocialSisterYi/CxKitty#64]
请问如果在线非本地题库接口，请求格式为json，例如：
题库url：https://lyck6.cn/scriptService/api/autoFreeAnswer
请求：{"question": "电影蒙太奇时期的代表作"}
返回：{
    "timestamp": 1695802610192,
    "code": 0,
    "message": "请求成功",
    "result": {
        "group": "860951928",
        "num": -1,
        "answers": [
            [
                "《仙女国》、《火车大劫案》、《罢工》"
            ],
            [
                "《战舰波将金号》"
            ],
            [
                "对"
            ],
            [
                "对"
            ],
            [
                "唐璜"
            ]
        ],
        "success": false
    }
}
应如何添加在config.yml内，谢谢
![image](https://github.com/SocialSisterYi/CxKitty/assets/66981884/d225fead-6a46-4550-bf24-e7e46a2bee1f)

**Comment by SocialSisterYi** [comment]
目前暂不支持以 json 格式的请求体搜索在线题库，仅支持 url query 格式请求

**Comment by SocialSisterYi** [comment]
可以再开一个 Issue，提议支持在线 REST API 搜索器支持以 json 作为请求体
