### ISSUE TITLE
修正作业未检索回答的文档请求

### ISSUE THREAD

**Issue by tsurumi-yizhou** [SocialSisterYi/CxKitty#68]
当在题库中无法检索到现有题目时，CxKitty的行为是导出后跳过。

期望README文档中提供能够在手动提供到处的题目的答案后重新运行的说明。虽然没有阅读过源码，但揣测是在mistake的json中修正后重新运行。

**Comment by SocialSisterYi** [comment]
这个逻辑是导出全部的未匹配答案，不存在自动运行的机制，自动导出的错题题单 .json 是方便用户二次搜索活排错，并合进题库数据库
