### ISSUE TITLE
登陆选择科目后报错

### ISSUE THREAD

**Issue by Maysec** [SocialSisterYi/CxKitty#7]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/53160265/204524362-0c5dd1d5-206a-4bf5-a144-b3f2223a9b13.png">

**Comment by SocialSisterYi** [comment]
请检查你的 JSON 题库格式，每道题的题目为 key 而 value 为答案，如
```json
{
    "题目1": "答案1",
    "题目2": "答案2"
}
```

**Comment by vimopqe** [comment]
![image](https://user-images.githubusercontent.com/116261739/204687276-e491a1a2-78b8-4384-8192-959d3bc92cae.png)

**Comment by Shellc0d** [comment]
题库问题解决了 又遇到了这个问题
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/53160265/205451765-2ee896d4-ad5b-4ba8-a87c-b95f57b3098b.png">

**Comment by SocialSisterYi** [comment]
尝试打断点调试并查看经过 JSON 解析的 attachment data 数据，检查是否有`jobid`字段，若不存在检查正常使用学习通web前端访问该视频是否可播放或者是否计入任务点完成情况

**Comment by xiaoyue2019** [comment]
How much did you know our GEGE so hard-working is?
