### ISSUE TITLE
怎么使用导出的题目搭建本地题库

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#73]

**Comment by SocialSisterYi** [comment]
导出的题目仅包含 题目文本`value` 题目类型`type` 选项`options` 这三个字段，目前已经填充过答案并保存的题目可以导出答案字段`answer`（暂不支持已批阅），可以使用导出的题单自行搜索，或者搭建一个题库后端使用接口调用，也可以合并到json题库

**Comment by XXXXBully** [comment]
导出的题目以及答案不是js格式的吗，怎么适配成可以搜索的类型呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月14日(周六) 晚上10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 怎么使用导出的题目搭建本地题库 (Issue #73)




 
导出的题目仅包含 题目文本value 题目类型type 选项options 这三个字段，目前已经填充过答案并保存的题目可以导出答案字段answer（暂不支持已批阅），可以使用导出的题单自行搜索，或者搭建一个题库后端使用接口调用，也可以合并到json题库
