### ISSUE TITLE
部分课程任务点无法读取，提示“未开放”

### ISSUE THREAD

**Issue by cyxnzb** [SocialSisterYi/CxKitty#74]
提示：
xxx。未开放，程序无法继续执行！
然后程序退出
只能手动去cx打开该节之后才能继续运行程序
（PS：该门课老师也挺🐕的，实际上这节课啥内容都没有）
<img width="395" alt="image" src="https://github.com/SocialSisterYi/CxKitty/assets/51886383/36371c1c-f575-4256-887c-68468f759f2b">
<img width="565" alt="image" src="https://github.com/SocialSisterYi/CxKitty/assets/51886383/d1c73f3e-b71a-46b2-b200-2a7bf84d85aa">

**Comment by cyxnzb** [comment]
基本上都是子节有问题，子小节读取正常
<img width="380" alt="image" src="https://github.com/SocialSisterYi/CxKitty/assets/51886383/419ec822-278a-4f12-b117-c3219e47124b">

**Comment by 1563dfghjm** [comment]
这个应该是遇到空白页了，你们有没有什么好的方法解决

**Comment by cyxnzb** [comment]
> 这个应该是遇到空白页了，你们有没有什么好的方法解决

目前的话。好像只能手动去看这个空白的，再用程序刷

**Comment by 1563dfghjm** [comment]
x = self.session.get(
                    url=f"https://mooc1-2.chaoxing.com/mooc-ans/mycourse/studentstudyAjax?courseId={self.course_id}&clazzid={self.class_id}&chapterId={self.chapters[int(index)-int(count)].chapter_id}&cpi={self.cpi}&verificationcode=")
                time.sleep(1)
                self.session.get(
                    url=f"https://mooc1.chaoxing.com/mooc-ans/mycourse/studentstudycourselist?courseId={self.course_id}&chapterId={self.chapters[int(index)-int(count)].chapter_id}&clazzid={self.class_id}&cpi={self.cpi}")
                time.sleep(1)
使用这个就能过，但是就是怎么判断这个什么状态用这，现在就很头疼

**Comment by SocialSisterYi** [comment]
可以发邮件提供一下出现该问题的账号吗？我这边有空调试一下

**Comment by cyxnzb** [comment]
> 可以发邮件提供一下出现该问题的账号吗？我这边有空调试一下

该怎么发给您

**Comment by SocialSisterYi** [comment]
> > 可以发邮件提供一下出现该问题的账号吗？我这边有空调试一下
> 
> 该怎么发给您

发送账号+密码到我的邮箱`shakaianee@qq.com`

**Comment by cyxnzb** [comment]
> > > 可以发邮件提供一下出现该问题的账号吗？我这边有空调试一下
> > 
> > 
> > 该怎么发给您
> 
> 发送账号+密码到我的邮箱`shakaianee@qq.com`

已发，不对的话我再给您重发

**Comment by SocialSisterYi** [comment]
经过测试，发现如果强行跳过没开放的章节，那么接下来后续的章节 Attachment 就无法解析，获取不到相应的参数，也就没有办法执行任何自动处理了

<img width="1270" alt="image" src="https://github.com/SocialSisterYi/CxKitty/assets/45892418/c84fc351-a4e0-4521-b3f3-2dbc66df6f89">

所以你的具体问题是遇到枝章节报错但叶章节可以解析，还是说任务执行完毕但无法解锁新的章节？

**Comment by cyxnzb** [comment]
> 任务执行完毕但无法解锁新的章节

应该是这个，即“任务执行完毕但无法解锁新的章节”，因为按理说刷课的话，是按课程章节顺序进行模拟播放，但是如果有空的章节的话，程序似乎就无法进行继续执行

**Comment by cyxnzb** [comment]
> x = self.session.get( url=f"[https://mooc1-2.chaoxing.com/mooc-ans/mycourse/studentstudyAjax?courseId={self.course_id}&clazzid={self.class_id}&chapterId={self.chapters[int(index)-int(count)].chapter_id}&cpi={self.cpi}&verificationcode=](https://mooc1-2.chaoxing.com/mooc-ans/mycourse/studentstudyAjax?courseId=%7Bself.course_id%7D&clazzid=%7Bself.class_id%7D&chapterId=%7Bself.chapters%5Bint(index)-int(count)%5D.chapter_id%7D&cpi=%7Bself.cpi%7D&verificationcode=)") time.sleep(1) self.session.get( url=f"[https://mooc1.chaoxing.com/mooc-ans/mycourse/studentstudycourselist?courseId={self.course_id}&chapterId={self.chapters[int(index)-int(count)].chapter_id}&clazzid={self.class_id}&cpi={self.cpi}](https://mooc1.chaoxing.com/mooc-ans/mycourse/studentstudycourselist?courseId=%7Bself.course_id%7D&chapterId=%7Bself.chapters%5Bint(index)-int(count)%5D.chapter_id%7D&clazzid=%7Bself.class_id%7D&cpi=%7Bself.cpi%7D)") time.sleep(1) 使用这个就能过，但是就是怎么判断这个什么状态用这，现在就很头疼

这是什么，应该怎么用

**Comment by SocialSisterYi** [comment]
经过调试，发现遇到带锁的空章节时，向该 url 发送 GET 请求即可解决`https://mooc1-2.chaoxing.com/mooc-ans/mycourse/studentstudyAjax?courseId={course_id}&clazzid={class_id}&chapterId={chapter_id}&cpi={cpi}&verificationcode=`，其中`course_id`、`class_id`、`cpi`与课程相关，`chapter_id`即欲解锁章节的 id

这里不需要判断什么情况下请求，因为在任何情况下，获取章节任务点之前访问该 url 都是可行的
