### ISSUE TITLE
提示TypeError: MukeSearcher.__init__() got an unexpected keyword argument 'file_path'

### ISSUE THREAD

**Issue by vimopqe** [SocialSisterYi/CxKitty#75]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Python\xxtym\CxKitty\main.py:362 in <module>                                                  │
│                                                                                                  │
│   359 │   │   for task_obj in ClassSelector(command, classes):                                   │
│   360 │   │   │   # 章节容器 执行章节任务                                                        │
│   361 │   │   │   if isinstance(task_obj, ChapterContainer):                                     │
│ ❱ 362 │   │   │   │   fuck_task_worker(task_obj)                                                 │
│   363 │   │   │                                                                                  │
│   364 │   │   │   # 考试对象 执行考试任务                                                        │
│   365 │   │   │   elif isinstance(task_obj, ExamDto):                                            │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\main.py:197 in fuck_task_worker                                          │
│                                                                                                  │
│   194 │   │   │   │   │   │   │   │   continue                                                   │
│   195 │   │   │   │   │   │   │   task_point.fetch_all()                                         │
│   196 │   │   │   │   │   │   │   # 实例化解决器                                                 │
│ ❱ 197 │   │   │   │   │   │   │   resolver = QuestionResolver(                                   │
│   198 │   │   │   │   │   │   │   │   exam_dto=task_point,                                       │
│   199 │   │   │   │   │   │   │   │   fallback_save=config.WORK["fallback_save"],                │
│   200 │   │   │   │   │   │   │   │   fallback_fuzzer=config.WORK["fallback_fuzzer"],            │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\resolver\question.py:185 in __init__                                     │
│                                                                                                  │
│   182 │   │   self.persubmit_delay = persubmit_delay                                             │
│   183 │   │   self.auto_final_submit = auto_final_submit                                         │
│   184 │   │   self.cb_confirm_submit = cb_confirm_submit                                         │
│ ❱ 185 │   │   self.searcher = load_searcher()  # 从配置文件加载搜索器                            │
│   186 │   │                                                                                      │
│   187 │   │   self.tui_ctx = Layout(name="Resolver")  # 当前类所属 TUI 的 ctx                    │
│   188 │   │   self.mistakes = []                                                                 │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\resolver\question.py:63 in load_searcher                                 │
│                                                                                                  │
│    60 │   │   │   raise AttributeError(f'Searcher "{typename}" not found')                       │
│    61 │   │   del searcher_conf["type"]                                                          │
│    62 │   │   # 动态加载搜索器类                                                                 │
│ ❱  63 │   │   searcher.add(SEARCHERS[typename](**searcher_conf))                                 │
│    64 │                                                                                          │
│    65 │   return searcher                                                                        │
│    66                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: MukeSearcher.__init__() got an unexpected keyword argument 'file_path'

**Comment by SocialSisterYi** [comment]
请按照最新 commit 中的 config.yml 配置，如使用搜索器类型`MukeSearcher`，应该附带`token`字段，而不是`file_path`
