### ISSUE TITLE
AttributeError: module 'jsonpath' has no attribute 'compile'

### ISSUE THREAD

**Issue by vimopqe** [SocialSisterYi/CxKitty#76]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ D:\Python\xxtym\CxKitty\main.py:362 in <module>                                                  │
│                                                                                                  │
│   359 │   │   for task_obj in ClassSelector(command, classes):                                   │
│   360 │   │   │   # 章节容器 执行章节任务                                                        │
│   361 │   │   │   if isinstance(task_obj, ChapterContainer):                                     │
│ ❱ 362 │   │   │   │   fuck_task_worker(task_obj)                                                 │
│   363 │   │   │                                                                                  │
│   364 │   │   │   # 考试对象 执行考试任务                                                        │
│   365 │   │   │   elif isinstance(task_obj, ExamDto):                                            │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\main.py:197 in fuck_task_worker                                          │
│                                                                                                  │
│   194 │   │   │   │   │   │   │   │   continue                                                   │
│   195 │   │   │   │   │   │   │   task_point.fetch_all()                                         │
│   196 │   │   │   │   │   │   │   # 实例化解决器                                                 │
│ ❱ 197 │   │   │   │   │   │   │   resolver = QuestionResolver(                                   │
│   198 │   │   │   │   │   │   │   │   exam_dto=task_point,                                       │
│   199 │   │   │   │   │   │   │   │   fallback_save=config.WORK["fallback_save"],                │
│   200 │   │   │   │   │   │   │   │   fallback_fuzzer=config.WORK["fallback_fuzzer"],            │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\resolver\question.py:185 in __init__                                     │
│                                                                                                  │
│   182 │   │   self.persubmit_delay = persubmit_delay                                             │
│   183 │   │   self.auto_final_submit = auto_final_submit                                         │
│   184 │   │   self.cb_confirm_submit = cb_confirm_submit                                         │
│ ❱ 185 │   │   self.searcher = load_searcher()  # 从配置文件加载搜索器                            │
│   186 │   │                                                                                      │
│   187 │   │   self.tui_ctx = Layout(name="Resolver")  # 当前类所属 TUI 的 ctx                    │
│   188 │   │   self.mistakes = []                                                                 │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\resolver\question.py:63 in load_searcher                                 │
│                                                                                                  │
│    60 │   │   │   raise AttributeError(f'Searcher "{typename}" not found')                       │
│    61 │   │   del searcher_conf["type"]                                                          │
│    62 │   │   # 动态加载搜索器类                                                                 │
│ ❱  63 │   │   searcher.add(SEARCHERS[typename](**searcher_conf))                                 │
│    64 │                                                                                          │
│    65 │   return searcher                                                                        │
│    66                                                                                            │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\resolver\searcher\restapi.py:214 in __init__                             │
│                                                                                                  │
│   211 │   "Muke在线搜索器"                                                                       │
│   212 │                                                                                          │
│   213 │   def __init__(self) -> None:                                                            │
│ ❱ 214 │   │   super().__init__(                                                                  │
│   215 │   │   │   url="https://api.muketool.com/cx/v2/query",                                    │
│   216 │   │   │   headers={                                                                      │
│   217 │   │   │   │   "Host": "api.muketool.com",                                                │
│                                                                                                  │
│ D:\Python\xxtym\CxKitty\resolver\searcher\restapi.py:97 in __init__                              │
│                                                                                                  │
│    94 │   │   │   self.session.headers.update(headers)                                           │
│    95 │   │   self.q_field = q_field                                                             │
│    96 │   │   self.o_field = o_field                                                             │
│ ❱  97 │   │   self.rsp_query = jsonpath.compile(a_field)                                         │
│    98 │   │   self.ext_params = ext_params or {}                                                 │
│    99 │                                                                                          │
│   100 │   def invoke(self, question: QuestionModel) -> SearcherResp:                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'jsonpath' has no attribute 'compile'

**Comment by SocialSisterYi** [comment]
请使用 poetry 构建项目依赖，如果使用 pip 安装依赖时，请安装 jsonpath-python，而不是 jsonpath
