### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by yuzhicy** [SocialSisterYi/CxKitty#78]

**Comment by yuzhicy** [comment]
<img width="611" alt="9e59d33faff9c0987734e8116bc0bbad" src="https://github.com/SocialSisterYi/CxKitty/assets/144519188/6cad4a9f-503f-420c-b8b2-5ad9fc7c0f43">题库配置如图

**Comment by SocialSisterYi** [comment]
清按照 yaml 语法标准填写配置，`q_field`和`o_field`是接口提交表单的字段，不应该把 demo 数据填写进去
