### ISSUE TITLE
适配冷月题库之后无法正常运行，log查看日志提示至少选择一个搜索器

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#79]
![微信图片_20231104151546](https://github.com/SocialSisterYi/CxKitty/assets/99703693/3ac0e9d5-e2ad-43d7-9215-eef0537b4e01)
![微信图片_20231104151821](https://github.com/SocialSisterYi/CxKitty/assets/99703693/4a706bd4-362b-4dec-9253-8821f1487daa)

**Comment by jixishi** [comment]
你没有注意缩进

**Comment by jixishi** [comment]
yaml使用缩进分级

**Comment by XXXXBully** [comment]
我试过了适配其他题库都OK，唯独冷月



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月10日(周五) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 适配冷月题库之后无法正常运行，log查看日志提示至少选择一个搜索器 (Issue #79)




 
yaml使用缩进分级

**Comment by NonFelm** [comment]
> 我试过了适配其他题库都OK，唯独冷月
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年11月10日(周五) 下午3:41 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [SocialSisterYi/CxKitty] 适配冷月题库之后无法正常运行，log查看日志提示至少选择一个搜索器 (Issue #79) yaml使用缩进分级 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，请问enncy题库正常吗，我有点数为啥用不了？
