### ISSUE TITLE
带锁🔒的树干章节能自动解锁之后，需要重新登录账号才能继续运行，跳过之后无法连贯完成任务点

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#81]

**Comment by XXXXBully** [comment]
有个小想法，就是能不能加个中控台，可以批量登录账号，并且查看每个任务点进度，然后修复解锁章节之后不能连贯完成任务点bug

**Comment by SocialSisterYi** [comment]
> 有个小想法，就是能不能加个中控台，可以批量登录账号，并且查看每个任务点进度，然后修复解锁章节之后不能连贯完成任务点bug

这个需求与本项目无关，本项目只实现 API 接口访问和自动接管，暂时无开发任务调度和管理平台的计划

以及不建议在同个 Issue 中反馈不同的问题

**Comment by SocialSisterYi** [comment]
在使用哪个版本出现该问题？是最新 commit 还是 release 0.4.4，另外出现该 bug 的具体现象是什么，解锁后跳过应执行的章节还是程序无法继续执行？有无报错？

**Comment by XXXXBully** [comment]
> 在使用哪个版本出现该问题？是最新 commit 还是 release 0.4.4，另外出现该 bug 的具体现象是什么，解锁后跳过应执行的章节还是程序无法继续执行？有无报错？

是0.44版本的，我看过log上面的提示是无法拉取视频进度，然后重新登录又可以继续刷，主要体现为自动掉线，所以我觉得刷完能不能就是他执行完毕或者执行不了了不要自动退出可以继续挂载在后台，之后也可以知道是哪个账号出了问题有什么问题都好找一点
