### ISSUE TITLE
提议任务结束之后不要自动退出，出现任何给问题之后保留脚本页面不要自动退出

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#82]
以上的建议在个人角度上看可以更容易查到脚本出错的原因，更好的去溯源相应账户的log

**Comment by SocialSisterYi** [comment]
程序出错时退出即方便使用docker监控任务状态，这样设计更合理，如需要debug，请使用IDE内置的调试工具或查看log，而不是保留抛出异常的traceback在终端
