### ISSUE TITLE
还是会出现需要手动解锁章节的问题

### ISSUE THREAD

**Issue by cyxnzb** [SocialSisterYi/CxKitty#85]
版本的话是最新的版本V0.44

**Comment by cyxnzb** [comment]
作者需要账号测试的话可以留个方式，不过上次给予的还能用

**Comment by cyxnzb** [comment]
另：感觉是偶发情况，因为我跑了三个号，就我自己的号会出现这个问题

**Comment by SocialSisterYi** [comment]
尝试在`main.py`中的168行，把`chap.refresh_chapter(index)`改为`chap.refresh_chapter(index-1)`
