### ISSUE TITLE
doker

### ISSUE THREAD

**Issue by FanyuanCode** [SocialSisterYi/CxKitty#86]
这是我的问题还是？
![tianruo_2023-11-17-638358616568015376](https://github.com/SocialSisterYi/CxKitty/assets/88940016/b5a00ffc-5037-4611-af2f-99bfa8598235)

**Comment by SocialSisterYi** [comment]
请不要使用docker desktop直接运行容器

**Comment by FanyuanCode** [comment]
我尝试过在在终端启动不过报了一样的错误，我看了文档，好像并没有强制做某些配置才能启动？能说说我该怎么启动吗，谢谢
