### ISSUE TITLE
Exceeded 30 redirects

### ISSUE THREAD

**Issue by FanyuanCode** [SocialSisterYi/CxKitty#88]
我在docker Desktop可以启动，但是在使用ubuntu中使用docker启动时，在输入完密码后就会显示TooManyRedirects: Exceeded 30 redirects.，这为什么会重定向，这是服务器网络问题吗？

**Comment by SocialSisterYi** [comment]
请检查你的主机网络配置和网络环境，以及容器的网络配置，可以使用`docker inspect`查询

**Comment by FanyuanCode** [comment]
"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "ff8163c2adedcfe39a86dcd88e375c5c1ad7fb50a61d1644c884d68c0c88806a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/ff8163c2aded",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "9d262bcc224d655d7cf39c3120374db9afa94b46aa85e914bfc0011adad2e1c7",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }这应该是容器的网络配置部分，但是我没看出具体哪里有问题，只能请教一下
