### ISSUE TITLE
新版本0.45bug

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#97]
新版本0.45bug，账号管理器无法使用，会随机自动登录某一个历史账号，无法自行选择登录或者新登录其他账号

**Comment by SocialSisterYi** [comment]
该项目不存在`v0.45`版本，这里应该指的是`v0.4.5`，经测试该版本直接使用 python 运行、使用 docker 构建镜像运行、使用 pyinstaller 编译后的可执行文件运行，均无法复现此 BUG

请检查是否使用其他管理程序通过 pipeline 方式调用该项目启动，向 stdin 缓冲区内写入了错误的数据

**Comment by XXXXBully** [comment]
易姐不更新了吗

**Comment by SocialSisterYi** [comment]
> 易姐不更新了吗

最近忙于工作，工作稳定前应该不会更新，另外已经在计划V0.5的更新了，这个会做大的调整不兼容之前的版本，计划创建新的branch
