### ISSUE TITLE
这是什么问题，突然给我提示个这

### ISSUE THREAD

**Issue by 1583581232** [SocialSisterYi/CxKitty#98]
![image](https://github.com/SocialSisterYi/CxKitty/assets/119564588/79226881-9f50-4186-a5a4-95d7a8f0acfc)

**Comment by SocialSisterYi** [comment]
麻烦提供一下log文件

**Comment by 1583581232** [comment]
> 麻烦提供一下log文件

麻烦了麻烦了，我自己已经解决了。原本以为是代码的问题，看这报的错误，后来又看了看发现不是，是网站的视频转码失败加载不出来，网页的问题。
